### ISSUE TITLE
Recent changes to the Style Guide index page make it much less useful 

### ISSUE THREAD

**Issue by terribly** [wet-boew/wet-boew-styleguide#312]
Now in the correct repository:

The recent changes to the Style Guide index page have made this page MUCH less useful.

It is a key reference page. It is now much harder to scan. It puts items of less common use and of lesser import into the list with things that are more important. The three column layout is very hard to scan.

I recommend reverting this to the prior index page. It was not something that needed fixing. The BREADCRUMBS however, do need to be fixed as they are a mess and this has a direct impact on usability as well.

**Comment by cfarquharson** [comment]
Hey @terribly 

The guide was updated to be more fulsome.  It's previous version was painfully out-of-date, in English only, and missing vast amounts of content/context.   

As the principle creator of the both the original Style Guide (the one you prefer) and this new Style Guide (the one you are commenting one), all I can say is that this is an open source solution and so if you have modifications you would like to see, you can contribute to the project.  To date, almost no one has participated in the project and so the output is based on what a few collaborators have put forward. 

One reason for this tiled design, is it allows actual examples of the components to be featured where possible.  Words like "Badges", "Equalize", "Absolute positioning" etc are seemingly vague and may not mean anything to anyone without additional up-front context.

From a functionality stance, if you are having a hard time with finding the design component you want, you can use filter box and type in our keywords. 
![filter-screenshot](https://cloud.githubusercontent.com/assets/2319199/19871312/9695f8dc-9f71-11e6-851e-bc0248a9d698.jpg)

**Comment by cfarquharson** [comment]
@terribly PS the breadcrumbs have been fixed by Service Canada.
Thanks a ton @shawnthompson - you rock!

**Comment by terribly** [comment]
Tiling makes scanning very difficult. The Table of Contents approach is a much better one. This is not the terminal page, it is to get to the sections. Seeing examples is not really essential at this point - it is just eye candy that gets in the way of navigation. 

Most people who will be coming to this on a regular basis will know what the elements are. This page is not the teaching page, it is to get to the goods. It also puts things in A-Z order without any sense of what are the key things that people are using. Perhaps some analytics would help understand what is most important. A-Z does not help when trying to find text specific things. Or layout. In this respect, the previous page was superior in its organization of the component parts.

**Comment by terribly** [comment]
Although the intentions might be good, I think the realization was not. But more importantly, the breadcrumb links are still broken. So fixing real problems and developing better content examples is probably a better use of time.

**Comment by cfarquharson** [comment]
@terribly which page has broken breadcrumbs because they work for me?  (You might have to refresh the page if you have it cached).

As far as the design, as I mentioned, this is an open course collaborative solution.  Feel free to submit coding changes.  That said, while I agree that 'people who will be coming to this on a regular basis will know what the elements are', from what I have seen on Canada.ca and other WET4 pages outside of Canada.ca, is there is a lack of continuity in the use of elements and a lack of understanding of what the elements are.  Developers naturally use the options they are familiar with and repeat them over an over again, even when other solutions would have worked better.  So the 'teaching' and 'eye candy' you referring was deemed important because WET4 elements are regularly misunderstood and misused. 

As far as performing analytics etc, I simply don't have time. This redesigned, bilingual, more robust and comprehensive guide was months of work as it was and I have other priorities to focus on. Again, if you want to champion this, you are free to do so.  It must be maintained in its bilingual format.
