### ISSUE TITLE
File Upload translation

### ISSUE THREAD

**Issue by MartyBeanCSPS** [wet-boew/wet-boew-styleguide#409]
https://wet-boew.github.io/wet-boew-styleguide/design/forms-fr

![file upload](https://user-images.githubusercontent.com/102972504/196711089-d85de4d3-e400-4a56-ab43-9ae543a38bfd.jpg)

Is there a way to translate the text in the file upload button?

Thank you,
Marty

**Comment by joel-osc** [comment]
I think this is your browser language configuration.

**Comment by MartyBeanCSPS** [comment]
How do I change this so it displays properly?

**Comment by joel-osc** [comment]
That depends on your browser, in Firefox it is about:preferences... If you are expecting it to flip languages as you toggle between en and fr on your website it will not. It is fixed.

**Comment by MartyBeanCSPS** [comment]
When I change my preferred language to French
It still shows in English
https://wet-boew.github.io/wet-boew-styleguide/design/forms-fr

***@***.***

***@***.***

Any ideas?

Thanks,
Marty
